// Generated by gencpp from file jaka_msgs/ClearError.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_CLEARERROR_H
#define JAKA_MSGS_MESSAGE_CLEARERROR_H

#include <ros/service_traits.h>


#include <jaka_msgs/ClearErrorRequest.h>
#include <jaka_msgs/ClearErrorResponse.h>


namespace jaka_msgs
{

struct ClearError
{

typedef ClearErrorRequest Request;
typedef ClearErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearError
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::ClearError > {
  static const char* value()
  {
    return "0fff944f16f37b02ba85acd57d94215a";
  }

  static const char* value(const ::jaka_msgs::ClearError&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::ClearError > {
  static const char* value()
  {
    return "jaka_msgs/ClearError";
  }

  static const char* value(const ::jaka_msgs::ClearError&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::ClearErrorRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::ClearError >
template<>
struct MD5Sum< ::jaka_msgs::ClearErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::ClearError >::value();
  }
  static const char* value(const ::jaka_msgs::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::ClearErrorRequest> should match
// service_traits::DataType< ::jaka_msgs::ClearError >
template<>
struct DataType< ::jaka_msgs::ClearErrorRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::ClearError >::value();
  }
  static const char* value(const ::jaka_msgs::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::ClearErrorResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::ClearError >
template<>
struct MD5Sum< ::jaka_msgs::ClearErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::ClearError >::value();
  }
  static const char* value(const ::jaka_msgs::ClearErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::ClearErrorResponse> should match
// service_traits::DataType< ::jaka_msgs::ClearError >
template<>
struct DataType< ::jaka_msgs::ClearErrorResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::ClearError >::value();
  }
  static const char* value(const ::jaka_msgs::ClearErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_CLEARERROR_H
