// Generated by gencpp from file jaka_msgs/GetFK.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_GETFK_H
#define JAKA_MSGS_MESSAGE_GETFK_H

#include <ros/service_traits.h>


#include <jaka_msgs/GetFKRequest.h>
#include <jaka_msgs/GetFKResponse.h>


namespace jaka_msgs
{

struct GetFK
{

typedef GetFKRequest Request;
typedef GetFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFK
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::GetFK > {
  static const char* value()
  {
    return "10d9bfd5c1accf4678c49f520f9480b8";
  }

  static const char* value(const ::jaka_msgs::GetFK&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::GetFK > {
  static const char* value()
  {
    return "jaka_msgs/GetFK";
  }

  static const char* value(const ::jaka_msgs::GetFK&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::GetFKRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::GetFK >
template<>
struct MD5Sum< ::jaka_msgs::GetFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetFK >::value();
  }
  static const char* value(const ::jaka_msgs::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetFKRequest> should match
// service_traits::DataType< ::jaka_msgs::GetFK >
template<>
struct DataType< ::jaka_msgs::GetFKRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetFK >::value();
  }
  static const char* value(const ::jaka_msgs::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::GetFKResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::GetFK >
template<>
struct MD5Sum< ::jaka_msgs::GetFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetFK >::value();
  }
  static const char* value(const ::jaka_msgs::GetFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetFKResponse> should match
// service_traits::DataType< ::jaka_msgs::GetFK >
template<>
struct DataType< ::jaka_msgs::GetFKResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetFK >::value();
  }
  static const char* value(const ::jaka_msgs::GetFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_GETFK_H
