// Generated by gencpp from file jaka_msgs/GetFKResponse.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_GETFKRESPONSE_H
#define JAKA_MSGS_MESSAGE_GETFKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaka_msgs
{
template <class ContainerAllocator>
struct GetFKResponse_
{
  typedef GetFKResponse_<ContainerAllocator> Type;

  GetFKResponse_()
    : cartesian_pose()
    , message()  {
    }
  GetFKResponse_(const ContainerAllocator& _alloc)
    : cartesian_pose(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _cartesian_pose_type;
  _cartesian_pose_type cartesian_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::jaka_msgs::GetFKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaka_msgs::GetFKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFKResponse_

typedef ::jaka_msgs::GetFKResponse_<std::allocator<void> > GetFKResponse;

typedef boost::shared_ptr< ::jaka_msgs::GetFKResponse > GetFKResponsePtr;
typedef boost::shared_ptr< ::jaka_msgs::GetFKResponse const> GetFKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaka_msgs::GetFKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaka_msgs::GetFKResponse_<ContainerAllocator1> & lhs, const ::jaka_msgs::GetFKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cartesian_pose == rhs.cartesian_pose &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaka_msgs::GetFKResponse_<ContainerAllocator1> & lhs, const ::jaka_msgs::GetFKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaka_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::GetFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::GetFKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::GetFKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e3f3a6af4e0d3902203dceed3bf47e2";
  }

  static const char* value(const ::jaka_msgs::GetFKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e3f3a6af4e0d390ULL;
  static const uint64_t static_value2 = 0x2203dceed3bf47e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaka_msgs/GetFKResponse";
  }

  static const char* value(const ::jaka_msgs::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32[] cartesian_pose\n"
"string message\n"
;
  }

  static const char* value(const ::jaka_msgs::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cartesian_pose);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaka_msgs::GetFKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaka_msgs::GetFKResponse_<ContainerAllocator>& v)
  {
    s << indent << "cartesian_pose[]" << std::endl;
    for (size_t i = 0; i < v.cartesian_pose.size(); ++i)
    {
      s << indent << "  cartesian_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cartesian_pose[i]);
    }
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_GETFKRESPONSE_H
