// Generated by gencpp from file jaka_msgs/GetIKResponse.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_GETIKRESPONSE_H
#define JAKA_MSGS_MESSAGE_GETIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaka_msgs
{
template <class ContainerAllocator>
struct GetIKResponse_
{
  typedef GetIKResponse_<ContainerAllocator> Type;

  GetIKResponse_()
    : joint()
    , message()  {
    }
  GetIKResponse_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_type;
  _joint_type joint;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::jaka_msgs::GetIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaka_msgs::GetIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIKResponse_

typedef ::jaka_msgs::GetIKResponse_<std::allocator<void> > GetIKResponse;

typedef boost::shared_ptr< ::jaka_msgs::GetIKResponse > GetIKResponsePtr;
typedef boost::shared_ptr< ::jaka_msgs::GetIKResponse const> GetIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaka_msgs::GetIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaka_msgs::GetIKResponse_<ContainerAllocator1> & lhs, const ::jaka_msgs::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaka_msgs::GetIKResponse_<ContainerAllocator1> & lhs, const ::jaka_msgs::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaka_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::GetIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dcff6f9f3dc05bbc7189ed764e58d40";
  }

  static const char* value(const ::jaka_msgs::GetIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dcff6f9f3dc05bbULL;
  static const uint64_t static_value2 = 0xc7189ed764e58d40ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaka_msgs/GetIKResponse";
  }

  static const char* value(const ::jaka_msgs::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32[] joint\n"
"string message\n"
;
  }

  static const char* value(const ::jaka_msgs::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaka_msgs::GetIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaka_msgs::GetIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint[i]);
    }
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_GETIKRESPONSE_H
