// Generated by gencpp from file jaka_msgs/GetIO.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_GETIO_H
#define JAKA_MSGS_MESSAGE_GETIO_H

#include <ros/service_traits.h>


#include <jaka_msgs/GetIORequest.h>
#include <jaka_msgs/GetIOResponse.h>


namespace jaka_msgs
{

struct GetIO
{

typedef GetIORequest Request;
typedef GetIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIO
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::GetIO > {
  static const char* value()
  {
    return "6ff1cb5f4f299720705884f0c89f9d08";
  }

  static const char* value(const ::jaka_msgs::GetIO&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::GetIO > {
  static const char* value()
  {
    return "jaka_msgs/GetIO";
  }

  static const char* value(const ::jaka_msgs::GetIO&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::GetIORequest> should match
// service_traits::MD5Sum< ::jaka_msgs::GetIO >
template<>
struct MD5Sum< ::jaka_msgs::GetIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetIO >::value();
  }
  static const char* value(const ::jaka_msgs::GetIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetIORequest> should match
// service_traits::DataType< ::jaka_msgs::GetIO >
template<>
struct DataType< ::jaka_msgs::GetIORequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetIO >::value();
  }
  static const char* value(const ::jaka_msgs::GetIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::GetIOResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::GetIO >
template<>
struct MD5Sum< ::jaka_msgs::GetIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetIO >::value();
  }
  static const char* value(const ::jaka_msgs::GetIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetIOResponse> should match
// service_traits::DataType< ::jaka_msgs::GetIO >
template<>
struct DataType< ::jaka_msgs::GetIOResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetIO >::value();
  }
  static const char* value(const ::jaka_msgs::GetIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_GETIO_H
