// Generated by gencpp from file jaka_msgs/GetIK.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_GETIK_H
#define JAKA_MSGS_MESSAGE_GETIK_H

#include <ros/service_traits.h>


#include <jaka_msgs/GetIKRequest.h>
#include <jaka_msgs/GetIKResponse.h>


namespace jaka_msgs
{

struct GetIK
{

typedef GetIKRequest Request;
typedef GetIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIK
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::GetIK > {
  static const char* value()
  {
    return "33a7ddff09d4b5dc0322950ee926aea6";
  }

  static const char* value(const ::jaka_msgs::GetIK&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::GetIK > {
  static const char* value()
  {
    return "jaka_msgs/GetIK";
  }

  static const char* value(const ::jaka_msgs::GetIK&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::GetIKRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::GetIK >
template<>
struct MD5Sum< ::jaka_msgs::GetIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetIK >::value();
  }
  static const char* value(const ::jaka_msgs::GetIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetIKRequest> should match
// service_traits::DataType< ::jaka_msgs::GetIK >
template<>
struct DataType< ::jaka_msgs::GetIKRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetIK >::value();
  }
  static const char* value(const ::jaka_msgs::GetIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::GetIKResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::GetIK >
template<>
struct MD5Sum< ::jaka_msgs::GetIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::GetIK >::value();
  }
  static const char* value(const ::jaka_msgs::GetIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::GetIKResponse> should match
// service_traits::DataType< ::jaka_msgs::GetIK >
template<>
struct DataType< ::jaka_msgs::GetIKResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::GetIK >::value();
  }
  static const char* value(const ::jaka_msgs::GetIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_GETIK_H
