// Generated by gencpp from file jaka_msgs/Move.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_MOVE_H
#define JAKA_MSGS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <jaka_msgs/MoveRequest.h>
#include <jaka_msgs/MoveResponse.h>


namespace jaka_msgs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::Move > {
  static const char* value()
  {
    return "bfcaec3e81ace5826d9d96166632c9d1";
  }

  static const char* value(const ::jaka_msgs::Move&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::Move > {
  static const char* value()
  {
    return "jaka_msgs/Move";
  }

  static const char* value(const ::jaka_msgs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::MoveRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::Move >
template<>
struct MD5Sum< ::jaka_msgs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::Move >::value();
  }
  static const char* value(const ::jaka_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::MoveRequest> should match
// service_traits::DataType< ::jaka_msgs::Move >
template<>
struct DataType< ::jaka_msgs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::Move >::value();
  }
  static const char* value(const ::jaka_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::MoveResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::Move >
template<>
struct MD5Sum< ::jaka_msgs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::Move >::value();
  }
  static const char* value(const ::jaka_msgs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::MoveResponse> should match
// service_traits::DataType< ::jaka_msgs::Move >
template<>
struct DataType< ::jaka_msgs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::Move >::value();
  }
  static const char* value(const ::jaka_msgs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_MOVE_H
