// Generated by gencpp from file jaka_msgs/ServoMoveEnable.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_SERVOMOVEENABLE_H
#define JAKA_MSGS_MESSAGE_SERVOMOVEENABLE_H

#include <ros/service_traits.h>


#include <jaka_msgs/ServoMoveEnableRequest.h>
#include <jaka_msgs/ServoMoveEnableResponse.h>


namespace jaka_msgs
{

struct ServoMoveEnable
{

typedef ServoMoveEnableRequest Request;
typedef ServoMoveEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoMoveEnable
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::ServoMoveEnable > {
  static const char* value()
  {
    return "0fff944f16f37b02ba85acd57d94215a";
  }

  static const char* value(const ::jaka_msgs::ServoMoveEnable&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::ServoMoveEnable > {
  static const char* value()
  {
    return "jaka_msgs/ServoMoveEnable";
  }

  static const char* value(const ::jaka_msgs::ServoMoveEnable&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::ServoMoveEnableRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::ServoMoveEnable >
template<>
struct MD5Sum< ::jaka_msgs::ServoMoveEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::ServoMoveEnable >::value();
  }
  static const char* value(const ::jaka_msgs::ServoMoveEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::ServoMoveEnableRequest> should match
// service_traits::DataType< ::jaka_msgs::ServoMoveEnable >
template<>
struct DataType< ::jaka_msgs::ServoMoveEnableRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::ServoMoveEnable >::value();
  }
  static const char* value(const ::jaka_msgs::ServoMoveEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::ServoMoveEnableResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::ServoMoveEnable >
template<>
struct MD5Sum< ::jaka_msgs::ServoMoveEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::ServoMoveEnable >::value();
  }
  static const char* value(const ::jaka_msgs::ServoMoveEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::ServoMoveEnableResponse> should match
// service_traits::DataType< ::jaka_msgs::ServoMoveEnable >
template<>
struct DataType< ::jaka_msgs::ServoMoveEnableResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::ServoMoveEnable >::value();
  }
  static const char* value(const ::jaka_msgs::ServoMoveEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_SERVOMOVEENABLE_H
