// Generated by gencpp from file jaka_msgs/SetCollision.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_SETCOLLISION_H
#define JAKA_MSGS_MESSAGE_SETCOLLISION_H

#include <ros/service_traits.h>


#include <jaka_msgs/SetCollisionRequest.h>
#include <jaka_msgs/SetCollisionResponse.h>


namespace jaka_msgs
{

struct SetCollision
{

typedef SetCollisionRequest Request;
typedef SetCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCollision
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::SetCollision > {
  static const char* value()
  {
    return "192c4b02f65b62b6f0470ca351b4f7cc";
  }

  static const char* value(const ::jaka_msgs::SetCollision&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::SetCollision > {
  static const char* value()
  {
    return "jaka_msgs/SetCollision";
  }

  static const char* value(const ::jaka_msgs::SetCollision&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::SetCollisionRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::SetCollision >
template<>
struct MD5Sum< ::jaka_msgs::SetCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetCollision >::value();
  }
  static const char* value(const ::jaka_msgs::SetCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetCollisionRequest> should match
// service_traits::DataType< ::jaka_msgs::SetCollision >
template<>
struct DataType< ::jaka_msgs::SetCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetCollision >::value();
  }
  static const char* value(const ::jaka_msgs::SetCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::SetCollisionResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::SetCollision >
template<>
struct MD5Sum< ::jaka_msgs::SetCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetCollision >::value();
  }
  static const char* value(const ::jaka_msgs::SetCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetCollisionResponse> should match
// service_traits::DataType< ::jaka_msgs::SetCollision >
template<>
struct DataType< ::jaka_msgs::SetCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetCollision >::value();
  }
  static const char* value(const ::jaka_msgs::SetCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_SETCOLLISION_H
