// Generated by gencpp from file jaka_msgs/SetIORequest.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_SETIOREQUEST_H
#define JAKA_MSGS_MESSAGE_SETIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaka_msgs
{
template <class ContainerAllocator>
struct SetIORequest_
{
  typedef SetIORequest_<ContainerAllocator> Type;

  SetIORequest_()
    : signal()
    , type(0)
    , index(0)
    , value(0.0)  {
    }
  SetIORequest_(const ContainerAllocator& _alloc)
    : signal(_alloc)
    , type(0)
    , index(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _signal_type;
  _signal_type signal;

   typedef int16_t _type_type;
  _type_type type;

   typedef int16_t _index_type;
  _index_type index;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::jaka_msgs::SetIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaka_msgs::SetIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIORequest_

typedef ::jaka_msgs::SetIORequest_<std::allocator<void> > SetIORequest;

typedef boost::shared_ptr< ::jaka_msgs::SetIORequest > SetIORequestPtr;
typedef boost::shared_ptr< ::jaka_msgs::SetIORequest const> SetIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaka_msgs::SetIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaka_msgs::SetIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaka_msgs::SetIORequest_<ContainerAllocator1> & lhs, const ::jaka_msgs::SetIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal &&
    lhs.type == rhs.type &&
    lhs.index == rhs.index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaka_msgs::SetIORequest_<ContainerAllocator1> & lhs, const ::jaka_msgs::SetIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaka_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_msgs::SetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_msgs::SetIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_msgs::SetIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a23f9d016f4490877e120633050e191a";
  }

  static const char* value(const ::jaka_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa23f9d016f449087ULL;
  static const uint64_t static_value2 = 0x7e120633050e191aULL;
};

template<class ContainerAllocator>
struct DataType< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaka_msgs/SetIORequest";
  }

  static const char* value(const ::jaka_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string signal\n"
"int16 type\n"
"int16 index\n"
"float32 value\n"
"\n"
;
  }

  static const char* value(const ::jaka_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
      stream.next(m.type);
      stream.next(m.index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaka_msgs::SetIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaka_msgs::SetIORequest_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.signal);
    s << indent << "type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.type);
    s << indent << "index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.index);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_SETIOREQUEST_H
