// Generated by gencpp from file jaka_msgs/SetTcpFrame.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_SETTCPFRAME_H
#define JAKA_MSGS_MESSAGE_SETTCPFRAME_H

#include <ros/service_traits.h>


#include <jaka_msgs/SetTcpFrameRequest.h>
#include <jaka_msgs/SetTcpFrameResponse.h>


namespace jaka_msgs
{

struct SetTcpFrame
{

typedef SetTcpFrameRequest Request;
typedef SetTcpFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTcpFrame
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::SetTcpFrame > {
  static const char* value()
  {
    return "3d15cf469e59f026a4e4b350932a8496";
  }

  static const char* value(const ::jaka_msgs::SetTcpFrame&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::SetTcpFrame > {
  static const char* value()
  {
    return "jaka_msgs/SetTcpFrame";
  }

  static const char* value(const ::jaka_msgs::SetTcpFrame&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::SetTcpFrameRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::SetTcpFrame >
template<>
struct MD5Sum< ::jaka_msgs::SetTcpFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetTcpFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetTcpFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetTcpFrameRequest> should match
// service_traits::DataType< ::jaka_msgs::SetTcpFrame >
template<>
struct DataType< ::jaka_msgs::SetTcpFrameRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetTcpFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetTcpFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::SetTcpFrameResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::SetTcpFrame >
template<>
struct MD5Sum< ::jaka_msgs::SetTcpFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetTcpFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetTcpFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetTcpFrameResponse> should match
// service_traits::DataType< ::jaka_msgs::SetTcpFrame >
template<>
struct DataType< ::jaka_msgs::SetTcpFrameResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetTcpFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetTcpFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_SETTCPFRAME_H
