// Generated by gencpp from file jaka_msgs/SetUserFrame.msg
// DO NOT EDIT!


#ifndef JAKA_MSGS_MESSAGE_SETUSERFRAME_H
#define JAKA_MSGS_MESSAGE_SETUSERFRAME_H

#include <ros/service_traits.h>


#include <jaka_msgs/SetUserFrameRequest.h>
#include <jaka_msgs/SetUserFrameResponse.h>


namespace jaka_msgs
{

struct SetUserFrame
{

typedef SetUserFrameRequest Request;
typedef SetUserFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUserFrame
} // namespace jaka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaka_msgs::SetUserFrame > {
  static const char* value()
  {
    return "f74c56afc671b9ccd78097ad9fa9b7ce";
  }

  static const char* value(const ::jaka_msgs::SetUserFrame&) { return value(); }
};

template<>
struct DataType< ::jaka_msgs::SetUserFrame > {
  static const char* value()
  {
    return "jaka_msgs/SetUserFrame";
  }

  static const char* value(const ::jaka_msgs::SetUserFrame&) { return value(); }
};


// service_traits::MD5Sum< ::jaka_msgs::SetUserFrameRequest> should match
// service_traits::MD5Sum< ::jaka_msgs::SetUserFrame >
template<>
struct MD5Sum< ::jaka_msgs::SetUserFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetUserFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetUserFrameRequest> should match
// service_traits::DataType< ::jaka_msgs::SetUserFrame >
template<>
struct DataType< ::jaka_msgs::SetUserFrameRequest>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetUserFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaka_msgs::SetUserFrameResponse> should match
// service_traits::MD5Sum< ::jaka_msgs::SetUserFrame >
template<>
struct MD5Sum< ::jaka_msgs::SetUserFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaka_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetUserFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaka_msgs::SetUserFrameResponse> should match
// service_traits::DataType< ::jaka_msgs::SetUserFrame >
template<>
struct DataType< ::jaka_msgs::SetUserFrameResponse>
{
  static const char* value()
  {
    return DataType< ::jaka_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::jaka_msgs::SetUserFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JAKA_MSGS_MESSAGE_SETUSERFRAME_H
